name: msreport
channels:
  - defaults
dependencies:
  - python=3.8.10
  - pip:
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - monai==0.9.0
    - nibabel==4.0.1
    - numpy==1.23.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - pandas==1.4.3
    - psutil==5.9.8
    - scikit-learn==1.1.1
    - scipy==1.9.0
    - seaborn==0.11.2
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchvision==0.14.0
    - tqdm==4.64.0
